### ISSUE TITLE
Core: We should find a replacement for semver due to its size

### ISSUE THREAD

**Issue by clebert** [sinnerschrader/feature-hub#130]

**Comment by fahrradflucht** [comment]
More as a note to myself. [I converted the `semver` package to es modules](https://github.com/fahrradflucht/es-semver) and split it up as much as possible. The result is published as `es-semver` to npm. Sadly the tree shaking size reduction isn't great. We indirectly use all the classes and can only shake of a few of the helper methods.

Those are my measurements:

Before:
`48602 Dec 16 19:49 feature-service-registry.js`
`20818 Dec 16 19:43 feature-service-registry.min.js`
`6001 Dec 16 19:43 feature-service-registry.min.js.gz`

After:
`40617 Dec 16 19:47 feature-service-registry.js`
`20230 Dec 16 19:46 feature-service-registry.min.js`
`5335 Dec 16 19:46 feature-service-registry.min.js.gz`

Looking at those numbers I'm not sure if this is worth maintaining the fork. I don't really think the npm folks are ready to accept a PR converting the upstream lib to esmodules, given the current state of es modules in node and the fact that this mean they would have to build which currently isn't the case.

I think we should really think about what feature set we need in terms version comparison. We currently ship support for all kinds of ranges but if we require that everyone adheres to semver then there is no need to interpret dependency declarations in any other way then `^`.

**Comment by KingHenne** [comment]
Rewriting the module and avoiding classes would probably yield better results with regards to tree shaking. I’m not sure it’s worth it though.

**Comment by KingHenne** [comment]
I just investigates a bit: The test line coverage of `node-semver` is 98.66 % (according to Jest). When removing all tests that are unrelated to `coerce`/`satisfies`, only 66.11 % of all lines are covered. So there does seem to be potential to create a reduced semver feature set that fits our requirements.
