### ISSUE TITLE
Core: Validate Consumer Configs

### ISSUE THREAD

**Issue by unstubbable** [sinnerschrader/feature-hub#136]
Either the consumers or the integrator probably have the need to validate the consumer configs. We should discuss whether the Feature Hub should offer a technical solution (or maybe at least a recommendation) to do this efficiently.

These tools could be considered:

- [jsonschema](https://bundlephobia.com/result?p=jsonschema@1.2.4)
- [io-ts](https://bundlephobia.com/result?p=io-ts@1.4.2)
- [typescript-is](https://bundlephobia.com/result?p=typescript-is@0.7.14)
- [runtypes](https://bundlephobia.com/result?p=runtypes@3.1.2)

**Comment by KingHenne** [comment]
As part of this story we should also adapt existing Feature Services.

**Comment by unstubbable** [comment]
obsolete due to #500 and #504
