### ISSUE TITLE
Managing updates of externals by integrator deployment

### ISSUE THREAD

**Issue by stemey** [sinnerschrader/feature-hub#162]
Keeping react and other important dependency versions in sync across integrator and feature apps is a difficult task. This is even harder since deployments can usually not be synchronized in such a way that all apps and integrator are available in the new version at the same time. 
The situation will be easier to handle if all apps are available in the old and the new version at the same time and its only up to the integrator’s deployment to make the switch. The remaining issue is to actually reference the different versions. This could be done by global release names like ‘iceberg’ meaning all apps are upgrading to next major react and libraryx version. Applications would then be dynamically loaded from a parameterized path like /app/todomvc/{release}/index.js

**Comment by KingHenne** [comment]
Do you think this would affect the Feature Hub API or feature set somehow?
