### ISSUE TITLE
LocationTransformer

### ISSUE THREAD

**Issue by stemey** [sinnerschrader/feature-hub#199]
I would expect the LocationTransformer to return all consumerLocations for a given rootLocation and return the rootLocation for all consumerLocations. Also the names should reflect this bijective transformation more clearly like:

````
toRootLocation(consumerLocations: ConsumerLocation[]): RootLocation
fromRootLocation(rootLocation: RootLocation): ConsumerLocation[]
````

**Comment by KingHenne** [comment]
The transformer never operates on all consumers at once. Why do you have theses expectations? And what is your perspective or point of view for having them?

**Comment by stemey** [comment]
Should we reopen this to support navigating to two custom lcoations?

**Comment by unstubbable** [comment]
@stemey Let's discuss those details in #441.
