### ISSUE TITLE
All: Remove everything that was deprecated in 1.x 

### ISSUE THREAD

**Issue by unstubbable** [sinnerschrader/feature-hub#369]
- `@deprecated` annotations
- ~~all Feature Services: move `s2:logger` from `optionalDependencies.featureServices` to `dependencies.featureServices`~~
- ~~make `logger` options required everywhere to improve DX~~
- reorder params of `createRootLocation`:
    ```ts
  createRootLocation(
      currentRootLocation: history.Location,
      consumerLocation: history.Location | undefined,
      consumerUid: string
  ): history.LocationDescriptorObject;
    ```

**Comment by clebert** [comment]
fixed by #508, #510, and #511
