### ISSUE TITLE
DOM: Add unit tests for @feature-hub/dom

### ISSUE THREAD

**Issue by fahrradflucht** [sinnerschrader/feature-hub#394]
Currently `@feature-hub/dom` is only integration tested by testing the `integrator-dom` demo using puppeteer. This does not sufficiently cover all cases nor should it.

Since [JSDom does not sufficiently implement the web components spec](https://github.com/jsdom/jsdom/issues/1030) we can not write unit tests using jest on the server as we do for all other modules.

Therefore we should add unit tests which are executed in the browser using karma to achieve full coverage for the `@feature-hub/dom` package.

**Comment by KingHenne** [comment]
Work started in the [`jsdom-custom-elements` branch](https://github.com/sinnerschrader/feature-hub/tree/jsdom-custom-elements).
