### ISSUE TITLE
IE-11: @babel/polyfill is not working with feature-hub

### ISSUE THREAD

**Issue by neerajpathak77** [sinnerschrader/feature-hub#450]
We started using @feature-hub in our react application. But I am facing a problem with @babel/polyfill after adding  @feature-hub. Our application is not working on IE 11 now with 
@feature-hub. 

On adding the '@babel/polyfill'; the below error is thrown 

```
 Error: The required Feature Service "s2:serialized-state-manager" in the unsupported version range "^0.1.0" could not be bound to consumer "elli:integrator". The supported versions are ["1.0.0"].
    at FeatureServiceRegistry.bindFeatureService (feature-service-registry.js:172)
    at FeatureServiceRegistry.bindFeatureServices (feature-service-registry.js:94)
    at _callee2$ (integrator.jsx:82)
    at tryCatch (runtime.js:62)
    at Generator.invoke [as _invoke] (runtime.js:288)
    at Generator.prototype.(:3003/en/anonymous function) [as next] (webpack:///./node_modules/regenerator-runtime/runtime.js?:114:21)
    at asyncGeneratorStep (asyncToGenerator.js:3)
    at _next (asyncToGenerator.js:25)
    at eval (asyncToGenerator.js:32)
    at new Promise (<anonymous>)

 (anonymous)	@	integrator.jsx:133
(anonymous)	@	integrator.jsx:154
./frontend/src/integrator.jsx	@	integrator.js:118
__webpack_require__	@	integrator.js:30
(anonymous)	@	integrator.js:94
(anonymous)	@	integrator.js:97
webpackUniversalModuleDefinition	@	integrator.js:7
(anonymous)	@	integrator.js:10
```
As per the error, it says the version is less than 1 but I am using the latest version. below is my package.json

```
  "@feature-hub/async-ssr-manager": "^1.3.0",
    "@feature-hub/core": "^1.3.0",
    "@feature-hub/history-service": "^1.3.0",
    "@feature-hub/module-loader-amd": "^1.3.0",
    "@feature-hub/module-loader-commonjs": "^1.3.0",
    "@feature-hub/react": "^1.3.0",
    "@feature-hub/serialized-state-manager": "^1.3.0",
    "@feature-hub/server-request": "^1.3.0",
```

Thanks

**Comment by unstubbable** [comment]
It seems you have declared a wrong version range for "s2:serialized-state-manager" in the dependencies for the consumer "elli:integrator". Instead of "^0.1.0", you must specify a version range that satisfies the supported version "1.0.0", e.g. "^1.0.0".

**Comment by unstubbable** [comment]
Also, please note that the npm version of the package "@feature-hub/serialized-state-manager" is not relevant here. Instead, the provided Feature Service versions must be referenced in the dependencies. They are documented in the respective SharedFeatureServices interface, e.g. https://feature-hub.io/@feature-hub/interfaces/serialized_state_manager.sharedserializedstatemanager.html.

**Comment by neerajpathak77** [comment]
Thanks for the quick feedback :)

**Comment by neerajpathak77** [comment]
Closing issue, this was a version mismatch from me. Not an issue in lib. 
Many many thanks for quick help.
