### ISSUE TITLE
feature-hub is breaking on IE-11

### ISSUE THREAD

**Issue by neerajpathak77** [sinnerschrader/feature-hub#455]
We started using @feature-hub in our react application. But we are facing a problem with after adding @feature-hub. Our application is not working on IE 11 now with
it's throwing the below error

`eval("__webpack_require__.r(__webpack_exports__);\n/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, \"AsyncValue\", function() { return AsyncValue; });\n/**\n * An `AsyncValue` provides a promise and as soon as the promise resolves or\n * rejects, also exposes the returned value or error. It is useful for\n * accessing a promise value in a synchronous context.\n */\nclass AsyncValue {\n    constructor(promise, value, error) {\n        this.promise = promise;\n        this.value = value;\n        this.error = error;\n        promise.then(val => (this.value = val)).catch(err => (this.error = err));\n    }\n}\n//# sourceMappingURL=async-value.js.map\n\n//# sourceURL=webpack:///./node_modules/@feature-hub/core/lib/esm/async-value.js?");`

Can you please guide to resolve this. Thanks

**Comment by unstubbable** [comment]
This is not an error but source code of a bundle that was built by webpack. Can you also post the error from the IE 11 console?

**Comment by neerajpathak77** [comment]
IE-11 shows the error 
`SCRIPT1002: Syntax error
`
and on clicking on it redirects to the above error. 
below is the webpack

**Comment by neerajpathak77** [comment]
Thanks @unstubbable

**Comment by unstubbable** [comment]
We decided not to transpile the Feature Hub source code down to ES5. If we did this, we would degrade the performance for all modern browsers, especially with regards to asynchronous operations. Instead, we documented in [this FAQ entry](https://feature-hub.io/docs/help/faq#does-the-feature-hub-run-in-internet-explorer-11-ie11) how you can still support IE11 as a Feature Hub integrator.
