### ISSUE TITLE
History Service - Documentation doesn`t match to demo

### ISSUE THREAD

**Issue by haugthom** [sinnerschrader/feature-hub#473]
The documentation (https://feature-hub.io/docs/guides/sharing-the-browser-history)
of the history-service doesn`t match the demo (https://github.com/sinnerschrader/feature-hub/tree/master/packages/demos/src/history-service).

The documentation part uses react-router but the demo doesn`t.
It seems not to work with react router.

Can you please update the demo and use react router as well in the demo.

**Comment by unstubbable** [comment]
We will look into this.

**Comment by unstubbable** [comment]
Can you please have a look whether the integration of React Router in the [`history-service-demo-react-router`](https://github.com/sinnerschrader/feature-hub/tree/history-service-demo-react-router/packages/demos/src/history-service) branch answers your questions regarding the usage of the History Service with React Router?

**Comment by snajo** [comment]
I will check, thank you!
