### ISSUE TITLE
Support of manifest file for feature apps

### ISSUE THREAD

**Issue by haugthom** [sinnerschrader/feature-hub#475]
Instead of adding each file (js for client, js for ssr, css, etc.) in the feature-app loader, it maybe make sense to support a mainfest file.

For example with webpack-assets-manifest:
https://www.npmjs.com/package/webpack-assets-manifest 

**Example:**
`{
  "featureapp.js": "featureapp-9c68d5e8de1b810a80e4.js",
  "featureapp.node.js": "featureapp-9c68d5e8de1b810a80e4.js",
  "featureapp.css": "featureapp-9c68d5e8de1b810a80e4.css",
}`

**Instead of:**
`<FeatureAppLoader
  src="https://example.com/some-feature-app.js"  
  serverSrc="https://example.com/some-feature-app-node.js"  
/>`

**We could do following:**
`<FeatureAppLoader
  manifest="https://example.com/manifest.json"
/>`

**Comment by unstubbable** [comment]
Can you expand on this a bit? Did you intent to publish the manifest file and reference it on the `FeatureAppLoader` so that it is loaded before the files listed in the manifest are loaded?

**Comment by unstubbable** [comment]
We considered this in the initial design phase of the Feature Hub several months ago, but decided against it, mainly because of the additional request that would have to be made for every Feature App.

It also has other disadvantages regarding topics like version pinning, supporting different absolute URLs, forcing a bundle filename, etc.

**Comment by snajo** [comment]
Is the first point really a problem in age of h2?
I cannot follow your arguments for the next points, can you provide examples?

**Comment by unstubbable** [comment]
> Is the first point really a problem in age of h2?

Yes, because the two requests for a Feature App have to be done sequentially, even with HTTP/2 this will be slower than a single request.

**Comment by snajo** [comment]
> > Is the first point really a problem in age of h2?
> 
> Yes, because the two requests for a Feature App have to be done sequentially, even with HTTP/2 this will be slower than a single request.

That is clear for me. But as we have an integrator and a feature app team (which can be different teams), as a feature team i would like to add an additional css without to change the FeatureAppLoader configuration in the integrator. It would decrease the dependencies between the teams.

Maybe you have a better idea?

**Comment by clebert** [comment]
Closed by me due to inactivity. Please reopen if there are further discussion points.
