### ISSUE TITLE
Proposal: Breaking change of beforeCreate

### ISSUE THREAD

**Issue by clebert** [sinnerschrader/feature-hub#490]
Maybe it would be better to pass the whole environment to `beforeCreate` instead of just the bound feature services. The environment is also the argument for the `create` method and contains potentially useful information.

New:

```ts
readonly beforeCreate?: (
  consumerUid: string,
  env: FeatureAppEnvironment<TConfig, TInstanceConfig, TFeatureServices>
) => void;
```

Current:

```ts
readonly beforeCreate?: (
  consumerUid: string,
  featureServices: FeatureServices
) => void;
```

**Comment by unstubbable** [comment]
🤔 I kind of like the symmetry with the `create` method, but practically this has no advantage for the integrator since he provides all of the other four props (`config`, `instanceConfig`, `baseUrl`, and `idSpecifier`) directly.

**Comment by clebert** [comment]
But we only give the integrator the `consumerUid`. Which is a combination of the Feature App ID and the ID specifier. The method of combination is more or less an implementation detail. So there is no intended way for the integrator to get to the configs, etc. Because he doesn't know the Feature App ID yet.

**Comment by clebert** [comment]
Perhaps we should offer helper methods to combine or separate IDs?
