### ISSUE TITLE
ConsumerUid of feature apps

### ISSUE THREAD

**Issue by stemey** [sinnerschrader/feature-hub#495]
The consumerUid of feature apps is currently constructed from the feature app definition id and an id specifier. The main problem with this approach is, that a feature app is hard to reference by the integrator. The integrator defines the idSpecifier and the javascript url of the feature app. To derive the consumerUid from feature app definition the integrator must load the javascript  from the url.

I suggest to not prepend the feature app definition id to the idSpecifier if it is defined. This way it's the  integrator's responsibility to make sure the consumerUid is unique and it can manage references to feature apps.

**Comment by unstubbable** [comment]
How about we add an additional optional `consumerUid` prop that if defined is used instead of `id` with `idSpecifier`? In this case the Integrator would have to make sure that it is unique.

**Comment by stemey** [comment]
What is the purpose of idSpecifier in that case? The integrator should only manage one "id".

> How about we add an additional optional `consumerUid` prop that if defined is used instead of `id` with `idSpecifier`? In this case the Integrator would have to make sure that it is unique.
> […](#)
> On 20. May 2019, at 09:45, Stefan Meyer ***@***.***> wrote: The consumerUid of feature apps is currently constructed from the feature app definition id and an id specifier. Problems with this approach are, that a feature app is hard to reference. The integrator defines the idSpecifier and the javascript url of the feature app. To derive the consumerUid it must load the javascript and to find the feature app definition. I suggest to not prepend the feature app definition id to the idSpecifier if it is defined. — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by unstubbable** [comment]
In this case the idSpecifier wouldn’t be defined. Only one of the two props should be defined (or none).

**Comment by stemey** [comment]
I would prefer a simple API - remove "idSecifier" completely in favour of "consumerUid" as its use case is unclear.

**Comment by unstubbable** [comment]
Yes, but since this would be breaking we would need to do this in two steps (see #369).

**Comment by unstubbable** [comment]
I would still prefer if the integrator wouldn’t even need to have a global map of feature app consumerUids though. Can this be avoided through other design changes (outside the feature hub)?
