### ISSUE TITLE
module-loader-commonjs prevents running on read only filesystem

### ISSUE THREAD

**Issue by s2-ctraut** [sinnerschrader/feature-hub#503]
When running on a read only filesystem like aws lambda you get a write error.
In module-loader-commonjs/index.ts line 20 a mkdirp fails.

**Comment by mathiswiehl** [comment]
afaik we could just write to `/tmp` instead, couldn't we?

**Comment by unstubbable** [comment]
Yes, but we also need to adjust the module search path in this case. A fixed loader is currently in development/testing.
