### ISSUE TITLE
SSR: not able to render with multiple async calls

### ISSUE THREAD

**Issue by sachkadam99** [sinnerschrader/feature-hub#531]
We have Feature App with multiple initial async calls. So `async-ssr-manager` not waiting till to complete those calls. So not able to load application.

**Comment by elbkind** [comment]
This example assumes that you have a redux store available:
```
asyncSsrManager.scheduleRerender(
		new Promise(resolve => {
			store.subscribe(() => {
				const {someVarIndicatinAReadyState} = store.getState();
				if (someVarIndicatinAReadyState === true) {
					resolve();
				}
			});
		})
	);
```

**Comment by unstubbable** [comment]
By the way, this is a problem you must solve in general when doing SSR with asynchronous dependencies, it is not specific to the Feature Hub.

**Comment by elbkind** [comment]
@sachkadam99 : does this answer your question and we can close this?
