### ISSUE TITLE
FeatureAppLoader and FeatureAppContainer should validate the featureAppId

### ISSUE THREAD

**Issue by FrecksterGIT** [sinnerschrader/feature-hub#585]
The featureAppId has a unique constraint which is not validated when adding Feature-Apps. 
There is no warning or error message.

I could reproduce two different problems/errors when reusing an ID:

1. The second Feature-App is not bound to any Services. (This is to be expected.)
2. If the second Feature-App is inside a Feature-App with the same ID the Browser-Tab crashes.

**Comment by unstubbable** [comment]
1. is by design, see also https://feature-hub.io/docs/guides/integrating-the-feature-hub#featureappid
2. In this case you are rendering the same feature app infinitely. I don't see value in detecting this in the feature hub. Just don't do that.
