### ISSUE TITLE
Implement Module Loading via Webpack Module Federation

### ISSUE THREAD

**Issue by stemey** [sinnerschrader/feature-hub#626]
Webpack Module Federation was designed to support micro frontends.

**Benefits:**
Feature apps can load libraries and share them with others that therefore don't need to load those libraries. With the current externals solution only one single version of a library is supported to be shared and needs to be provided by the integrator as an external. Module Webpack Federation also supports version matching in identifying if a library can be shared.

**Comment by unstubbable** [comment]
released with [v2.9.0](https://github.com/sinnerschrader/feature-hub/releases/tag/v2.9.0)
