### ISSUE TITLE
How can I define a service inside "featureServiceDefinitions: []" that is being loaded from a remote location?

### ISSUE THREAD

**Issue by AndresHMosqueda** [sinnerschrader/feature-hub#655]
How can I define a service inside "featureServiceDefinitions: []" that is being loaded from a remote location?

As I'm getting:

**The Feature App module at the url "localhost:3004/myFeatureApp.js" has been successfully loaded.
**index.js:1 Error: The required Feature Service "test:helloService" is not registered and therefore could not be bound to consumer "test:hello-container".

![Screen Shot 2021-03-28 at 13 11 01](https://user-images.githubusercontent.com/42881305/112764693-147e0880-8fc7-11eb-8e01-e556c835db86.png)

![Screen Shot 2021-03-28 at 13 12 56](https://user-images.githubusercontent.com/42881305/112764764-56a74a00-8fc7-11eb-86e6-9de85053c52f.png)

**There is no good documentation on how to integrate this...

**Comment by unstubbable** [comment]
There are at least two options I can think of:

1. Publish the Feature Service as an npm package to a public or private npm registry, as you would do with any other JavaScript lib.
2. Build an AMD/UMD bundle out of the Feature Service Definition and fetch it from the remote location with `loadAmdModule`, e.g.:
    ```js
    (async () => {
      const { default: myFeatureServiceDefinition } = await loadAmdModule(
        "http://localhost:3004/myFeatureService.js"
      );

      const { featureAppManager } = createFeatureHub("test:container-integrator", {
        featureServiceDefinitions: [myFeatureServiceDefinition],
        moduleLoader: loadAmdModule,
        providedExternals: { react: "16.8.6", "@feature-hub/react": "2.8.1" },
      });

      // ...
    })().catch(console.error);
    ```

**Comment by AndresHMosqueda** [comment]
Thanks for the response @unstubbable, I added these lines but now I got:

**feature-service-registry.ts:163 Uncaught TypeError: Cannot read property 'id' of undefined

These are the lines I added:
![Screen Shot 2021-03-29 at 8 33 22](https://user-images.githubusercontent.com/42881305/112852916-9e7ead80-9069-11eb-8aa6-6440528b15aa.png)

This is the error in the browser:
![Screen Shot 2021-03-29 at 8 33 44](https://user-images.githubusercontent.com/42881305/112852931-a2aacb00-9069-11eb-9bae-0b79d88c814f.png)

Inside http://localhost:3004/myFeatureAppService.js file I see the id there:
![Screen Shot 2021-03-29 at 8 33 59](https://user-images.githubusercontent.com/42881305/112852949-a63e5200-9069-11eb-85bd-38753b98a439.png)

https://github.com/AndresHMosqueda/featureApp
https://github.com/AndresHMosqueda/feature-container-app

Do you know what is missing?

**Comment by unstubbable** [comment]
I'm sorry, but I can not guide you through every JavaScript issue you encounter. I'm fine with answering Feature Hub specific questions in these issues, but you need to be able to debug the non-specific issues, that can mostly be attributed to not having a lot of experience writing JavaScript applications, yourself.
