### ISSUE TITLE
https://feature-hub.io/ seems to be DOWN !!!!

### ISSUE THREAD

**Issue by shuklaj-vw** [sinnerschrader/feature-hub#658]
We're not able to access https://feature-hub.io/ since (04/01/2021) morning. Is there an isue going on? It keeps on giving 404 error. 

![image](https://user-images.githubusercontent.com/54860957/113450908-da4da600-93ce-11eb-879c-3cef7492fe29.png)

Hope it's not April Fool Prank stretched too far :) We really need this back please.

**Comment by unstubbable** [comment]
Thanks for the heads-up! It’s up and running again.
