### ISSUE TITLE
External modules not loaded correctly when referencing feature hub

### ISSUE THREAD

**Issue by ErikParso** [sinnerschrader/feature-hub#715]
Hi, we are dynamicaly loading some external module scripts by appending script tag to document during runtime.

    const script = document.createElement('script');
    script.src = src;
    script.id = scriptId;
    script.type = 'module';
    document.body.appendChild(script);
    script.onload = () => { resolve({}); };
    script.onerror = () => { reject(); }

Everything was working fine, script was appended to body like this

    <script src="https://finance-calculator/widgets/calculator-v2.min.js?v=2" id="FinanceCalculator" type="module"></script>

 action onLoad was invoked and module loaded into `window.ModuleName` variable from where it can be accessed

![image](https://user-images.githubusercontent.com/35962203/182355310-6a9c0f57-5fc2-43ee-9bce-cb2677fe3c96.png)

**After referencing feature hub**

Problem occures when I reference feature hub functionality somewhere in application. For example When I use createFeatureHub func somewhere (even though the line is not extecuted), external modules loading process as described above is not working anymore. 
* The script tag is appended correctly, 
* onLoad action is invoked, 
* module is not loaded into window (window.ModuleName is undefined)

Is there something in library that may break modules loading?

**Comment by unstubbable** [comment]
What kind of module loader have you defined in `createFeatureHub`?

**Comment by ErikParso** [comment]
> What kind of module loader have you defined in `createFeatureHub`?

It was an amdModuleLoader

**Comment by unstubbable** [comment]
This loader uses SystemJS under the hood which might interfere with your script if you also have an AMD implementation in there somewhere. If you have control over the integrator, which it sounds like since you are using `createFeatureHub`, I'd recommend to consider switching to the [Webpack Module Federation Loader](https://feature-hub.io/docs/guides/integrating-the-feature-hub#webpack-module-federation-loader).

**Comment by ErikParso** [comment]
Switched from ours approach and used `loadAmdModule` from `@feature-hub/module-loader-amd` instead. Worked like a charm. Thank you.
